# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-18 21:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expensereport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensereport',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expenseitem',
            name='hotel',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='expenseitem',
            name='meals',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='expenseitem',
            name='miscellaneous',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='expenseitem',
            name='telephone',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='expenseitem',
            name='transportation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
